"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from django.utils import timezone
import zoneinfo
timezone.activate(zoneinfo.ZoneInfo('Asia/Almaty'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!kj3rsqm21jck*!w3lps+21r$p!s3i0_j5xahkyxa714&-rj9n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']












# Application definition

INSTALLED_APPS = [
    
    'project1',
    
    'social_django',
    'crispy_forms',
    'ckeditor',
    'admin_reorder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    
]
"""
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '*****************************************************' # Google Consumer Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '**********************************************' # Google Consumer Secret
"""

MIDDLEWARE = [
     'admin_reorder.middleware.ModelAdminReorder',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'TIME_ZONE':'Asia/Almaty'
    }
}




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Email

EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='*********************'
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL='****************'
EMAIL_PORT=587
EMAIL_HOST_PASSWORD='*****************'

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Almaty'


DATETIME_FORMAT='Y-M-D h:i:s' 



USE_I18N = True

USE_L10N = False

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static_dev'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ADMIN_REORDER  = (
    'project1',
    
    {'app': 'project1', 'label': 'Добавление товара в главной странице ',
     'models': (
                'project1.Category',
                'project1.subcategories',
                'project1.Product',
                )
    },

    {'app': 'project1', 'label': 'Рекламный банер главной страницы',
     'models': ('project1.New_Recomedation',
     'project1.New_Recomendations2',)
    },
    {'app': 'project1', 'label': 'Клиенты интернет магазина',
     'models': ('project1.Customer',)
    },
    { 'app' : 'auth' , 'models' : (
    'auth.Group' ,
    { 'model' : 'auth.User' , 'label' : 'Главная пользователей' },
    )},
    
)

LIKES_OBJS_DICT = {'project1.models': ['Product']}
