# Generated by Django 4.0 on 2022-02-12 17:18

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'ordering': ['-final_price'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('birth_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления категории')),
            ],
            options={
                'verbose_name': 'Категорий',
                'verbose_name_plural': 'Категорий',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verificate', models.BooleanField(default=False, verbose_name='Почта потверждена')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('create_customer', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистраций')),
                ('birth_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистраций клиента')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='New_Recomedation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_text', models.CharField(max_length=75, verbose_name='Черный текст')),
                ('red_text', models.CharField(max_length=75, verbose_name='Красный текст')),
                ('images', models.ImageField(upload_to='', verbose_name='Изображение нового продукта')),
                ('birth_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добовления')),
            ],
            options={
                'verbose_name': 'Банер 1',
                'verbose_name_plural': 'Банер для реклам',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Главная изображение товара')),
                ('images_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дочерние изображения')),
                ('images_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дочерние изображения')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Новая цена')),
                ('count_product', models.DecimalField(decimal_places=0, default=1, max_digits=7, verbose_name='Количество товара')),
                ('history_price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Старая цена')),
                ('birth_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
                ('old_discount', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Цена до скидки')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Скидка в процентах')),
                ('discount_end_date', models.DateTimeField(default=datetime.datetime(2022, 2, 12, 23, 18, 36), verbose_name='Дата окончания скидки')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=8)),
                ('new', models.BooleanField(default=True, verbose_name='Новый продукт')),
                ('orders', models.DecimalField(decimal_places=0, default=0, max_digits=2000, verbose_name='Количество заказов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.category', verbose_name='Категория')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategories_slug', models.SlugField(unique=True)),
                ('subcategory', models.CharField(max_length=255, verbose_name='подкатегория')),
                ('birth_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления подкатегории')),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newses', to='project1.category', unique=True)),
            ],
            options={
                'verbose_name': 'Подкатегорий',
                'verbose_name_plural': 'Подкатегорий',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='REKLAMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.product', verbose_name='продукт каторый рекламируют')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
                'ordering': ['-products'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='project1.subcategories', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(default='+7(---)-- -- --', max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен')], default='new', max_length=100, verbose_name='Статус заказ')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(default=datetime.datetime(2022, 2, 12, 23, 18, 36), verbose_name='Дата получения заказа')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='project1.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='project1.Order', verbose_name='Заказы покупателя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст Коментария')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 2, 12, 17, 18, 36, 344667, tzinfo=utc), verbose_name='Дата создания комментария')),
                ('is_child', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_children', to='project1.comment', verbose_name='Родительски коментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='project1.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Продукты для корзины',
                'verbose_name_plural': 'Продукты для корзины',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='project1.CartProduct'),
        ),
    ]
