# Generated by Django 4.0 on 2022-02-13 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_category_content_type_category_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 5, 49, 39, 785034, tzinfo=utc), verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 11, 49, 39), verbose_name='Дата получения заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 11, 49, 39), verbose_name='Дата окончания скидки'),
        ),
    ]
