# Generated by Django 4.0 on 2022-03-07 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_remove_news_model_date_alter_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='new_recomedation',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Изображение нового продукта !! желательно 1920 на 800'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 7, 21, 0, 27), verbose_name='Дата получения заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 21, 0, 27), verbose_name='Дата окончания скидки'),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение 1171 на 300'),
        ),
    ]
