# Generated by Django 4.0 on 2022-02-13 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_alter_comment_timestamp_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 5, 51, 43, 285328, tzinfo=utc), verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 11, 51, 43), verbose_name='Дата получения заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 11, 51, 43), verbose_name='Дата окончания скидки'),
        ),
    ]
