# Generated by Django 4.0 on 2022-02-13 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_subcategories_category_next_alter_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='category_next',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 6, 35, 39, 130190, tzinfo=utc), verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 12, 35, 39), verbose_name='Дата получения заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 12, 35, 39), verbose_name='Дата окончания скидки'),
        ),
    ]
