# Generated by Django 4.0 on 2022-02-13 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project1', '0006_remove_subcategories_category_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fr_content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fr_content_type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='fr_object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 6, 54, 23, 911141, tzinfo=utc), verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 12, 54, 23), verbose_name='Дата получения заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 12, 54, 23), verbose_name='Дата окончания скидки'),
        ),
    ]
