# Generated by Django 4.0 on 2022-02-13 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0007_category_fr_content_type_category_fr_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fr_content_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fr_object_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 7, 1, 52, 79340, tzinfo=utc), verbose_name='Дата создания комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 13, 1, 52), verbose_name='Дата получения заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 13, 1, 52), verbose_name='Дата окончания скидки'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.category', unique=True),
        ),
    ]
